### PR TITLE
GitHub release on new tag at master

### PR DESCRIPTION
**Pull request by potsbo**
## WHY

We want automatic release via travis-ci, for this project is almost beta ready.

## WHAT

- [x] Add cross-build task
- [x] Invoke this on master with tag

### CODE REVIEW

**Comment by potsbo** [comment]
```console
make clean && make glide && make cross-build && make dist
```
produces

```console
potsbo@magi-INS-% ls -l dist/
total 52496
drwxr-xr-x  5 potsbo  staff      170 Jan 12 11:07 darwin-386/
drwxr-xr-x  5 potsbo  staff      170 Jan 12 11:07 darwin-amd64/
-rw-r--r--  1 potsbo  staff  2251333 Jan 12 11:07 developers-account-mapper-v0.1.0-darwin-386.tar.gz
-rw-r--r--  1 potsbo  staff  2259353 Jan 12 11:07 developers-account-mapper-v0.1.0-darwin-386.zip
-rw-r--r--  1 potsbo  staff  2396150 Jan 12 11:07 developers-account-mapper-v0.1.0-darwin-amd64.tar.gz
-rw-r--r--  1 potsbo  staff  2402378 Jan 12 11:07 developers-account-mapper-v0.1.0-darwin-amd64.zip
-rw-r--r--  1 potsbo  staff  2129092 Jan 12 11:07 developers-account-mapper-v0.1.0-linux-386.tar.gz
-rw-r--r--  1 potsbo  staff  2137987 Jan 12 11:07 developers-account-mapper-v0.1.0-linux-386.zip
-rw-r--r--  1 potsbo  staff  2271030 Jan 12 11:07 developers-account-mapper-v0.1.0-linux-amd64.tar.gz
-rw-r--r--  1 potsbo  staff  2276641 Jan 12 11:07 developers-account-mapper-v0.1.0-linux-amd64.zip
-rw-r--r--  1 potsbo  staff  2108791 Jan 12 11:07 developers-account-mapper-v0.1.0-windows-386.tar.gz
-rw-r--r--  1 potsbo  staff  2116848 Jan 12 11:07 developers-account-mapper-v0.1.0-windows-386.zip
-rw-r--r--  1 potsbo  staff  2253154 Jan 12 11:07 developers-account-mapper-v0.1.0-windows-amd64.tar.gz
-rw-r--r--  1 potsbo  staff  2260098 Jan 12 11:07 developers-account-mapper-v0.1.0-windows-amd64.zip
drwxr-xr-x  5 potsbo  staff      170 Jan 12 11:07 linux-386/
drwxr-xr-x  5 potsbo  staff      170 Jan 12 11:07 linux-amd64/
drwxr-xr-x  5 potsbo  staff      170 Jan 12 11:07 windows-386/
drwxr-xr-x  5 potsbo  staff      170 Jan 12 11:07 windows-amd64/
potsbo@magi-INS-% unzip -l dist/developers-account-mapper-v0.1.0-darwin-386.zip
Archive:  dist/developers-account-mapper-v0.1.0-darwin-386.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  01-12-2017 11:07   darwin-386/
  6352868  01-12-2017 11:07   darwin-386/developers-account-mapper
     1071  01-12-2017 11:07   darwin-386/LICENSE
      735  01-12-2017 11:07   darwin-386/README.md
---------                     -------
  6354674                     4 files
```

**Comment by potsbo** [comment]
GITHUB_TOKEN has been set at travis-ci.

**Comment by potsbo** [comment]
@dtan4 ready to be reviewed.

**Comment by dtan4** [comment]
Your changes looks good.

Please add a badge of GitHub Release in README 📝 [GitHub release](https://github.com/wantedly/developers-account-mapper/releases)

```markdown
[![GitHub release](https://img.shields.io/github/release/wantedly/developers-account-mapper.svg)](https://github.com/wantedly/developers-account-mapper/releases)
```

**Comment by potsbo** [comment]
It's been added
screen shot 2017-01-12 at 11 28 04
https://github.com/wantedly/developers-account-mapper/tree/0a59d46610e9410bb139d50c5a0a193aeac1cabc

**Comment by dtan4** [comment]
LGTM 👍

**Review by dtan4 — APPROVED** [review]

**Pull request merged**
