### PR TITLE
Add Slack user info

### PR DESCRIPTION
**Pull request by potsbo**
## WHY

We need to set not only GitHub username, but also SlackMention

## WHAT

- [x] Make GetUserByLoginName handle also Slack information

### CODE REVIEW

**Comment by potsbo** [comment]
My plan is to use this SlackMention() in exec command, which is currently in review process at https://github.com/wantedly/developers-account-mapper/pull/13

@dtan4 I will implement that later, which means this PR is ready.

**Comment by potsbo** [comment]
@dtan4 This PR is ready, please review and merge.

**Comment by dtan4** [comment]
It seems there is NO logical changes now... is it okay?

image

**Comment by potsbo** [comment]
@dtan4 
Since more than one PRs depend on each other, this branch has been fully merged in another PR, which means this PR is no longer making any sense and should be closed.
Sorry for letting you check sth like this...

**Pull request closed without merging**
